### ISSUE TITLE
GoogelFIt gives com.google.android.gms.common.api.ApiException: 5000: Application needs OAuth consent from the user Google Fit

### ISSUE THREAD

**Issue by brjichkar** [android/fit-samples#65]
Does anyone know in which situation com.google.android.gms.common.api.ApiException: 5000: Application needs OAuth consent from the user Google Fit this error come? 
I gave all the permission required but still giving me error. 
I am using sample program,

**Comment by rohitranjan1991** [comment]
@brjichkar , when in the google console. Can you please guide me on this. Am stuck on this.

**Comment by ShivShrivas** [comment]
@brjichkar have you got any solution for this

**Comment by ShivShrivas** [comment]
@rohitranjan1991 have you got any solution for this please help me. I'm stuck on this
